// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZ8HpxEQ7K8dGwFPPUCqVLmBHjRHhDmDI',
    appId: '1:387936145022:web:354aa70706ebd1ab9e522f',
    messagingSenderId: '387936145022',
    projectId: 'poc-mvvm-riverpod',
    authDomain: 'poc-mvvm-riverpod.firebaseapp.com',
    storageBucket: 'poc-mvvm-riverpod.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZgZdW_j7XVu0oWPZ2YZLxsvgH4_bLoak',
    appId: '1:387936145022:android:3391141331c0522e9e522f',
    messagingSenderId: '387936145022',
    projectId: 'poc-mvvm-riverpod',
    storageBucket: 'poc-mvvm-riverpod.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnxFQWJ74SdTVAvgCy8mgUMhEKIlsiAQw',
    appId: '1:387936145022:ios:b2fb7eeaa142d6a09e522f',
    messagingSenderId: '387936145022',
    projectId: 'poc-mvvm-riverpod',
    storageBucket: 'poc-mvvm-riverpod.appspot.com',
    iosBundleId: 'com.example.pocMvvmRiverpodArchitecture',
  );
}
